# Generated by Django 5.1.4 on 2025-01-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('yil', models.IntegerField()),
                ('km', models.IntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sehir', models.CharField(max_length=50)),
                ('kaza_raporu', models.CharField(max_length=50)),
                ('renk', models.CharField(max_length=20)),
                ('yakit_turu', models.CharField(max_length=20)),
                ('vites_turu', models.CharField(max_length=20)),
                ('arac_durumu', models.CharField(max_length=20)),
                ('takas_durumu', models.CharField(max_length=20)),
                ('cekis', models.CharField(max_length=20)),
                ('motor_hacmi', models.CharField(max_length=20)),
                ('motor_gucu', models.CharField(max_length=20)),
                ('kasa_tipi', models.CharField(max_length=20)),
                ('kimden', models.CharField(max_length=50)),
            ],
        ),
    ]
